INCLUDE "emu8086.inc"

TAMANHO EQU 32

org 100h

DEFINE_GET_STRING
DEFINE_PRINT_STRING

    MOV DI, OFFSET PALAVRA
    MOV DX, TAMANHO + 1
    CALL GET_STRING
   
    MOV SI, OFFSET PALAVRA
    CALL PULA_LINHA  
    
    
    ;MOV DI, OFFSET INICIO_A                                  
    ;CALL PROCURA_ESQUERDA_DIREITA
    ;MOV DI, OFFSET INICIO_A
    ;CALL PROCURA_CIMA_BAIXO
    ;MOV DI, OFFSET INICIO_B
    ;CALL PROCURA_DIREITA_ESQUERDA
    ;MOV DI, OFFSET INICIO_B
    ;CALL PROCURA_BAIXO_CIMA
    MOV DI, OFFSET INICIO_A
    CALL PROCURA_DIAGONAL
    
    
    CALL PULA_LINHA                                  
     

    MOV AH,4CH
    MOV AL, 0
    INT 21H



   
;ESQUERDA->DIREITA

PROCURA_ESQUERDA_DIREITA:
    PUSHF  
    PUSH DX
PROCURANDO_ESQUERDA_DIREITA_IGUAIS:
    MOV DL, [SI]
    MOV DH, [DI]
    CMP DL, 0
    JE  ACHOU_SUBSTRING_PROCURA_ESQUERDA_DIREITA
    CMP DH, 0
    JE  NAO_ACHOU_SUBSTRING_PROCURA_ESQUERDA_DIREITA
    CMP DH,DL
    JE  IGUAL_PARCIAL_PROCURANDO_ESQUERDA_DIREITA_IGUAIS
    MOV SI, OFFSET PALAVRA
    INC DI
    JMP PROCURANDO_ESQUERDA_DIREITA_IGUAIS
IGUAL_PARCIAL_PROCURANDO_ESQUERDA_DIREITA_IGUAIS:
    INC SI
    INC DI
    JMP PROCURANDO_ESQUERDA_DIREITA_IGUAIS
ACHOU_SUBSTRING_PROCURA_ESQUERDA_DIREITA:
    MOV AH,2
    MOV DL,"S"
    INT 21H
    JMP FIM_PROCURA_ESQUERDA_DIREITA
NAO_ACHOU_SUBSTRING_PROCURA_ESQUERDA_DIREITA:
    MOV AH,2
    MOV DL,"N"
    INT 21H
FIM_PROCURA_ESQUERDA_DIREITA:
    POP DX
    POPF
    RET


 

;DIREITA->ESQUERDA

PROCURA_DIREITA_ESQUERDA:
    PUSHF  
    PUSH DX
    CALL NAVEGA_ATE_FINAL    
PROCURANDO_DIREITA_ESQUERDA_IGUAIS:
    MOV DL, [SI]
    MOV DH, [DI]
    CMP DL, 0
    JE  ACHOU_SUBSTRING_PROCURA_DIREITA_ESQUERDA
    CMP DH, 0
    JE  NAO_ACHOU_SUBSTRING_PROCURA_DIREITA_ESQUERDA
    CMP DH,DL
    JE  IGUAL_PARCIAL_PROCURANDO_DIREITA_ESQUERDA_IGUAIS
    MOV SI, OFFSET PALAVRA
    DEC DI
    JMP PROCURANDO_DIREITA_ESQUERDA_IGUAIS
IGUAL_PARCIAL_PROCURANDO_DIREITA_ESQUERDA_IGUAIS:
    INC SI
    DEC DI
    JMP PROCURANDO_DIREITA_ESQUERDA_IGUAIS
ACHOU_SUBSTRING_PROCURA_DIREITA_ESQUERDA:
    MOV AH,2
    MOV DL,"S"
    INT 21H
    JMP FIM_PROCURA_DIREITA_ESQUERDA
NAO_ACHOU_SUBSTRING_PROCURA_DIREITA_ESQUERDA:
    MOV AH,2
    MOV DL,"N"
    INT 21H
FIM_PROCURA_DIREITA_ESQUERDA:
    POP DX
    POPF
    RET

 
 
 
;CIMA->BAIXO

PROCURA_CIMA_BAIXO:
    PUSHF  
    PUSH DX
PRIMEIRA_LINHA_CIMA_BAIXO:
    INC DI
    PUSH DI    
PROCURANDO_CIMA_BAIXO_IGUAIS:
    MOV DL, [SI]
    MOV DH, [DI]
    CMP DL, 0
    JE  ACHOU_SUBSTRING_PROCURA_CIMA_BAIXO
    CMP DH, 0
    JE  NAO_ACHOU_SUBSTRING_PROCURA_CIMA_BAIXO
    CMP DH, 23h ;#
    JE  NAO_ACHOU_SUBSTRING_PROCURA_CIMA_BAIXO
    CMP DH,DL
    JE  IGUAL_PARCIAL_PROCURANDO_CIMA_BAIXO_IGUAIS
    MOV SI, OFFSET PALAVRA
    CMP DH, 2Ah ;*
    JE RETORNA_PRIMEIRA_LINHA_CIMA_BAIXO ;Atingiu o fim da coluna
    ADD DI, 42
    JMP PROCURANDO_CIMA_BAIXO_IGUAIS
IGUAL_PARCIAL_PROCURANDO_CIMA_BAIXO_IGUAIS:
    INC SI
    ADD DI, 42
    JMP PROCURANDO_CIMA_BAIXO_IGUAIS
ACHOU_SUBSTRING_PROCURA_CIMA_BAIXO:
    MOV AH,2
    MOV DL,"S"
    INT 21H
    JMP FIM_PROCURA_CIMA_BAIXO
RETORNA_PRIMEIRA_LINHA_CIMA_BAIXO:
    POP DI
    JMP PRIMEIRA_LINHA_CIMA_BAIXO 
NAO_ACHOU_SUBSTRING_PROCURA_CIMA_BAIXO:
    MOV AH,2
    MOV DL,"N"
    INT 21H   
FIM_PROCURA_CIMA_BAIXO:
    POP DI
    POP DX
    POPF
    RET

 
 
 
;BAIXO->CIMA

PROCURA_BAIXO_CIMA:
    PUSHF  
    PUSH DX
    CALL NAVEGA_ATE_FINAL
PRIMEIRA_LINHA_BAIXO_CIMA:
    DEC DI
    PUSH DI    
PROCURANDO_BAIXO_CIMA_IGUAIS:
    MOV DL, [SI]
    MOV DH, [DI]
    CMP DL, 0
    JE  ACHOU_SUBSTRING_PROCURA_BAIXO_CIMA
    CMP DH, 0
    JE  NAO_ACHOU_SUBSTRING_PROCURA_BAIXO_CIMA
    CMP DH, 23h ;#
    JE  NAO_ACHOU_SUBSTRING_PROCURA_BAIXO_CIMA
    CMP DH,DL
    JE  IGUAL_PARCIAL_PROCURANDO_BAIXO_CIMA_IGUAIS
    MOV SI, OFFSET PALAVRA
    CMP DH, 24h ;$
    JE RETORNA_PRIMEIRA_LINHA_BAIXO_CIMA ;Atingiu o comeco da coluna
    SUB DI, 42
    JMP PROCURANDO_BAIXO_CIMA_IGUAIS
IGUAL_PARCIAL_PROCURANDO_BAIXO_CIMA_IGUAIS:
    INC SI
    SUB DI, 42
    JMP PROCURANDO_BAIXO_CIMA_IGUAIS
ACHOU_SUBSTRING_PROCURA_BAIXO_CIMA:
    MOV AH,2
    MOV DL,"S"
    INT 21H
    JMP FIM_PROCURA_BAIXO_CIMA
RETORNA_PRIMEIRA_LINHA_BAIXO_CIMA:
    POP DI
    JMP PRIMEIRA_LINHA_BAIXO_CIMA 
NAO_ACHOU_SUBSTRING_PROCURA_BAIXO_CIMA:
    MOV AH,2
    MOV DL,"N"
    INT 21H   
FIM_PROCURA_BAIXO_CIMA:
    POP DI
    POP DX
    POPF
    RET




;PROCURA_DIAGONAL

PROCURA_DIAGONAL:
    PUSHF  
    PUSH DX
PROCURANDO_DIAGONAL_IGUAIS:
    MOV DL, [SI]
    MOV DH, [DI]
    CMP DH, 0
    JE  CONTABILIZA_ACERTOS_PROCURA_DIAGONAL
    CMP DH,DL
    JE  ENCONTROU_INICIO_PROCURANDO_DIAGONAL
    MOV SI, OFFSET PALAVRA
    INC DI
    JMP PROCURANDO_DIAGONAL_IGUAIS
ENCONTROU_INICIO_PROCURANDO_DIAGONAL:
    
    CALL VERIFICA_DIAGONAL_SUPERIOR_DIREITA
    CALL VERIFICA_DIAGONAL_INFERIOR_DIREITA
    CALL VERIFICA_DIAGONAL_INFERIOR_ESQUERDA
    CALL VERIFICA_DIAGONAL_SUPERIOR_ESQUERDA
    INC DI
    MOV SI, OFFSET PALAVRA
    JMP PROCURANDO_DIAGONAL_IGUAIS

CONTABILIZA_ACERTOS_PROCURA_DIAGONAL:
    CMP VEZES_ENCONTRADAS, 0
	JE NENHUM_ACERTO_PROCURA_DIAGONAL
	JMP FIM_PROCURA_DIAGONAL
	
NENHUM_ACERTO_PROCURA_DIAGONAL:
	MOV AH,2
    MOV DL,"N"
    INT 21H
	JMP FIM_PROCURA_DIAGONAL
ALGUM_ACERTO_PROCURA_DIAGONAL:
	MOV AH,2
    MOV DL,"S"
    INT 21H
FIM_PROCURA_DIAGONAL:
    POP DX
    POPF
    RET

VERIFICA_DIAGONAL_SUPERIOR_DIREITA:
    push di
    push si
    VERIFICANDO_DIAGONAL_SUPERIOR_DIREITA:
    INC SI   
    SUB DI, 41
    MOV DL, [SI]
    MOV DH, [DI]
    CMP DL, 0
    JE  ACHOU_SUBSTRING_PROCURA_DIAGONAL:
    CMP DH, DL
    JE VERIFICANDO_DIAGONAL_SUPERIOR_DIREITA
    JMP FIM_VERIFICACAO
    
VERIFICA_DIAGONAL_INFERIOR_DIREITA:
    push di
    push si
    VERIFICANDO_DIAGONAL_INFERIOR_DIREITA:
    INC SI   
    ADD DI, 43
    MOV DL, [SI]
    MOV DH, [DI]
    CMP DL, 0
    JE  ACHOU_SUBSTRING_PROCURA_DIAGONAL:
    CMP DH, DL
    JE VERIFICANDO_DIAGONAL_INFERIOR_DIREITA
    JMP FIM_VERIFICACAO
    
VERIFICA_DIAGONAL_INFERIOR_ESQUERDA:
    push di
    push si
    VERIFICANDO_DIAGONAL_INFERIOR_ESQUERDA:
    INC SI   
    ADD DI, 41
    MOV DL, [SI]
    MOV DH, [DI]
    CMP DL, 0
    JE  ACHOU_SUBSTRING_PROCURA_DIAGONAL:
    CMP DH, DL
    JE VERIFICANDO_DIAGONAL_INFERIOR_ESQUERDA
    JMP FIM_VERIFICACAO
    
VERIFICA_DIAGONAL_SUPERIOR_ESQUERDA:
    push di
    push si
    VERIFICANDO_DIAGONAL_SUPERIOR_ESQUERDA:
    INC SI   
    SUB DI, 43
    MOV DL, [SI]
    MOV DH, [DI]
    CMP DL, 0
    JE  ACHOU_SUBSTRING_PROCURA_DIAGONAL:
    CMP DH, DL
    JE VERIFICANDO_DIAGONAL_SUPERIOR_ESQUERDA
    JMP FIM_VERIFICACAO


ACHOU_SUBSTRING_PROCURA_DIAGONAL:
    MOV AH,2
    MOV DL,"S"
    INT 21H
    INC VEZES_ENCONTRADAS    

FIM_VERIFICACAO:
    pop si
    pop di
    RET
;-------------------------------

NAVEGA_ATE_FINAL:
    pushf
    push dx    
    
NAVEGACAO_ATE_FINAL:
    MOV DL, [DI]
    CMP DL, 40H ;@
    JE FIM_NAVEGA_ATE_FINAL:
    INC DI
    JMP NAVEGACAO_ATE_FINAL
    
FIM_NAVEGA_ATE_FINAL:
    pop dx
    popf
    RET

;-------------------------------

PULA_LINHA:                      
    pushf
    push ax
    push dx
    MOV AH,2
    MOV DL,13        
    INT 21H
    MOV AH,2
    MOV DL,10
    INT 21H
    pop dx        
    pop ax
    popf
    RET

PALAVRA DB TAMANHO DUP(" "),0  

                                                       
;use qualquer marcador                                                          
;fixo 10x40
         DB 0,"#$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$@"
INICIO_A DB   "!MSJDFLKASJDKFLJSADKLFJAKLSJDFKLASJDFKJSM@"
         DB   "!AIJDFLKASJDKFLJSADKLFJAKLSJDFKLASJDFKJII@"
         DB   "!ALGKDFJKLASDJFLKSAJDKFLJSADKLFJLKDSAJGLG@"
         DB   "!ASJUFLKASMIGUELJSADKLFJAKLSJDFKLESJMUKJU@"
         DB   "!ALLKELDFASDDJFLKSAJDKFLJSADKLFJLKUSEJFLE@"
         DB   "!ASEDELKASJDKFLJSADKLFJAKLSJDFKLASJGGKJSL@"
         DB   "!ALUUDFJKLASDJFLKSAJDKFLJSADKLFJLKDSIJFLK@"
         DB   "!ASGDFLKASJDKFLJSADKLFJAKLSJDFKLASJDEMJSA@"
         DB   "!AIIKDFJKLASDJFLKSAJDKFLJSALEUGIMKDSLJFLK@"
INICIO_B DB   "!MSMDFLKASJDKFLJSADKLFJAKLSJDFKLASJDFKJSA@"
         DB   "*****************************************#",0
         

LIN 	DB 0
COL 	DB 0
COR 	DB 0    
VEZES_ENCONTRADAS DB 0
             